development:
  adapter: postgresql
  encoding: unicode
  database: carsoft_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: carsoft_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: carsoft_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432
